# Generated by Django 3.1.3 on 2020-11-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Okr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(max_length=45)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'okr',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('remember_token', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik', models.IntegerField()),
                ('posision', models.CharField(max_length=45)),
                ('unit_level_1', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('band_posisi', models.CharField(max_length=45)),
                ('divisi', models.CharField(max_length=50)),
                ('direktorat', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('atasan_nik', models.CharField(max_length=45)),
                ('atasan_atasan_nik', models.CharField(max_length=45)),
                ('ldap_update', models.IntegerField()),
                ('is_firts_login', models.IntegerField()),
                ('is_change_agent', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='OkrOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcm.okr')),
            ],
            options={
                'db_table': 'okr_output',
            },
        ),
        migrations.AddField(
            model_name='okr',
            name='id_created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcm.users'),
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key_result', models.IntegerField()),
                ('key_result', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcm.okr')),
            ],
            options={
                'db_table': 'key_result',
            },
        ),
    ]
